# Generated by Django 4.0.4 on 2022-06-08 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userlinkips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddr', models.CharField(max_length=15, verbose_name='Ip Adres')),
                ('userdata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.userdata')),
            ],
        ),
    ]
