# Generated by Django 4.0.4 on 2022-05-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Link adi(sherti)')),
                ('link', models.URLField(verbose_name='Link')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Yerlesdirilme tarixi')),
                ('active', models.BooleanField(default=False, verbose_name='Aktiv?')),
                ('blok', models.BooleanField(default=False, verbose_name='Blok et')),
                ('slug', models.SlugField(verbose_name='Post slug')),
            ],
        ),
    ]
