# Generated by Django 4.0.4 on 2022-06-08 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_link_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkIpList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddr', models.CharField(max_length=15, verbose_name='Ip adres')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.link')),
            ],
        ),
    ]
